//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginRegistrationInMVCwithDatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Price { get; set; }
        public string Image { get; set; }
        public Nullable<int> Ctegory_ID { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
